### ISSUE TITLE
compilation matters

### ISSUE THREAD

**Issue by RobinDavid** [aziem/keystone-ocaml#2]
Hi  !

First of all, thanks for having done such a binding seems really cool. I wanted to try it for but didn't get to compile it. The `oasis setup` command failed with the following message:

```
W: Cannot find source file matching module 'Ffi_generated' in library keystone
W: Cannot find source file matching module 'Ffi_generated_types' in library keystone
```

Maybe you have an idea of where it is coming from ?

The make command also fail with:

```
File "keystone.mli", line 140, characters 61-88:
Error: Unbound type constructor result
Command exited with code 2.
```

I guess that result type is from the 4.03 OCaml version no ?
_(I am running 4.02.3 :cry: )_

**Comment by aziem** [comment]
> First of all, thanks for having done such a binding seems really cool. I wanted to try it for but didn't get to compile it. The `oasis setup` command failed with the following message:
> 
> ```
> W: Cannot find source file matching module 'Ffi_generated' in library keystone
> W: Cannot find source file matching module 'Ffi_generated_types' in library keystone
> ```
> 
> Maybe you have an idea of where it is coming from ?

These modules are autogenerated by the ctypes library: to access C enum values, we have to generate a C program which then generates an OCaml module. That way OCaml can access the actual values that enums take.  I haven't figured out how to remove the warning...but everything seems to be setup fine in spite of this warning.

> The make command also fail with:
> 
> ```
> File "keystone.mli", line 140, characters 61-88:
> Error: Unbound type constructor result
> Command exited with code 2.
> ```
> 
> I guess that result type is from the 4.03 OCaml version no ?
> _(I am running 4.02.3 :cry: )_

For OCaml < 4.03, you can install a result module using opam:

`opam install result`

This is a backported Result module for older versions of OCaml. This should fix your compile error. I should update the README to mention this....

**Comment by RobinDavid** [comment]
It worked !
I also added `Result` in the `_oasis` file on the `BuildDepends` line. Then I prefix all `Ok` and `Error` with `Result.` to avoid warnings.
That seems to be enough :wink:

Thank's

**Comment by aziem** [comment]
Cool! 

Sorry, I forgot to mention that the _oasis needs to be modified and the prefix issue: I am in the middle of moving these bindings into the Keystone repository and fixing these errors there.
